# Generated by Django 4.2.1 on 2023-06-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditos',
            old_name='monto',
            new_name='importe_credito',
        ),
    ]
