# Generated by Django 4.2.1 on 2023-06-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0003_alter_creditos_monto_cuota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditos',
            old_name='monto_cuota',
            new_name='importe_cuota',
        ),
    ]
