# Generated by Django 4.2.1 on 2023-06-08 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_creditos', '0004_rename_monto_cuota_creditos_importe_cuota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creditos',
            new_name='Credito',
        ),
    ]
