# Generated by Django 4.2.1 on 2023-06-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0005_rename_creditos_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='user',
        ),
    ]
