# Generated by Django 4.2.1 on 2023-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0007_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_cuota',
            name='fecha_vencimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
