# Generated by Django 4.2.1 on 2023-07-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0008_lista_cuota_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_cuota',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='lista_cuota',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CobroCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], max_length=10)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_creditos.credito')),
            ],
        ),
    ]
