# Generated by Django 4.2.1 on 2023-07-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0009_lista_cuota_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_cuota',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lista_cuota',
            name='monto_pagado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
