# Generated by Django 4.2.1 on 2023-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0010_lista_cuota_fecha_pago_lista_cuota_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrocuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobrocuota',
            name='monto_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista_cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lista_cuota',
            name='monto_pagado',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
