# Generated by Django 4.2.1 on 2023-12-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0012_cliente_celular_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_cuota',
            name='monto_pagado',
        ),
        migrations.DeleteModel(
            name='CobroCuota',
        ),
    ]
