# Generated by Django 4.2.1 on 2023-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0013_remove_lista_cuota_monto_pagado_delete_cobrocuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista_cuota',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
