# Generated by Django 4.2.1 on 2023-12-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0014_alter_lista_cuota_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_cuota',
            name='importe_actualizado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista_cuota',
            name='estado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('medio_pago', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_creditos.lista_cuota')),
            ],
        ),
    ]
